# This workflow is used to build & scan image using trivy vulnerability scanner and upload the results to github security tab

name: Build & Vulnerability Scan using Trivy Scanner

on:
  push:
    branches: [ main, release/*]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main, release/*]
  workflow_dispatch:
    branches: [ main, release/*]

jobs:
  build-scan-image:
    name: Build & Scan Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Set up JDK build environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
        
      - name: Maven Verify
        run: mvn -ntp clean verify

      #Build cmsint-pac-extractor image for scanning
      - name: Build cmsint-pac-extractor image from Dockerfile
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: .
        run: |
          docker build -t cmsint-pac-extractor:${{ github.sha }} --build-arg MVN_PROFILE=cmsint-pac-extractor ${CONTEXT}

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner for cmsint-pac-extractor
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: cmsint-pac-extractor:${{ github.sha }}
          #format: table
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      #Build cmsint-pac-transformer image for scanning
      - name: Build cmsint-pac-transformer image from Dockerfile
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: .
        run: |
          docker build -t cmsint-pac-transformer:${{ github.sha }} --build-arg MVN_PROFILE=cmsint-pac-transformer ${CONTEXT}

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner for cmsint-pac-transformer
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: cmsint-pac-transformer:${{ github.sha }}
          #format: table
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL
      
      #Build cmsint-pac-loader image for scanning
      - name: Build cmsint-pac-loader image from Dockerfile
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          CONTEXT: .
        run: |
          docker build -t cmsint-pac-loader:${{ github.sha }} --build-arg MVN_PROFILE=cmsint-pac-loader ${CONTEXT}

      #Run Vulnerability Scan usinig Trivy scanner
      - name: Run Trivy vulnerability scanner for cmsint-pac-loader
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: cmsint-pac-loader:${{ github.sha }}
          #format: table
          format: sarif
          output: trivy-results.sarif
          exit-code: 1
          ignore-unfixed: true
          severity: HIGH,CRITICAL

      #Upload results to the Github security tab.
      - name: Upload Trivy scan results to GitHub Security tab1
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results.sarif
